services:
  - type: web
    name: receipt-php-mindee
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MINDEE_API_KEY
        sync: false   # tu la saisis dans Render UI
